# Generated by Django 5.1.2 on 2025-01-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noclue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LogIn',
        ),
    ]
